sensor:
  - platform: mqtt
    name: soulsens_dpid104
    unique_id: soulsens_dpid104
    state_topic: soulsens/sound
    availability_topic: tele/your_tasmota_topic/LWT
    payload_available: Online
    payload_not_available: Offline
  - platform: template
    sensors:
      soulsens_dpid104_00:
        value_template: >
          {{ states('sensor.soulsens_dpid104')[0:2] }}
      soulsens_dpid104_01:
        value_template: >
          {{ states('sensor.soulsens_dpid104')[2:4] }}
      soulsens_dpid104_02:
        value_template: >
          {{ states('sensor.soulsens_dpid104')[4:6] }}
      soulsens_dpid104_03:
        value_template: >
          {{ states('sensor.soulsens_dpid104')[6:8] }}

# next try: Universal Media Player

light:
  - platform: template
    lights:
      soulsens_sound:
        friendly_name: "Soulsens Sound"
        value_template: >
          {% set val1 = ('0x' ~ states('sensor.soulsens_dpid104_00')) | int(base=16) %}
          {% if val1 == 1 %}
            ON
          {% else %}
            OFF
          {% endif %}
        level_template: >
          {% set value = ('0x' ~ states('sensor.soulsens_dpid104_02')) | int(base=16) %}
          {{ ((value|float)*255/15) | int }}
        effect_list_template: >
          {{ "['Ocean', 'Thunder', 'Rain', 'Stream','Rainforest','Wind','Deep space','Bird','Cricket','Whale','White Noise', 'Pink Noise','Fan','Hairdryer','Lullaby','Piano','Wind Chimes']" }}
        effect_template: >
          {% set value = ('0x' ~ states('sensor.soulsens_dpid104_01')) | int(base=16) %}
          {% if value == 1 %}
            Ocean
          {% elif value == 2 %}
            Thunder
          {% elif value == 3 %}
            Rain
          {% elif value == 4 %}
            Stream
          {% elif value == 5 %}
            Rainforest
          {% elif value == 6 %}
            Wind
          {% elif value == 7 %}
            Deep space
          {% elif value == 8 %}
            Bird
          {% elif value == 9 %}
            Cricket
          {% elif value == 10 %}
            Whale
          {% elif value == 11 %}
            White Noise
          {% elif value == 12 %}
            Pink Noise
          {% elif value == 13 %}
            Fan
          {% elif value == 14 %}
            Hairdryer
          {% elif value == 15 %}
            Lullaby
          {% elif value == 16 %}
            Piano
          {% elif value == 17 %}
            Wind Chimes
          {% endif %}
        turn_on:
          service: mqtt.publish
          data:
            topic: cmnd/your_tasmota_topic/SerialSend5
            retain: true
            payload_template: >
              {% set PRE = "55AA0006000868000004" %}
              {% set B00 = '01' %}
              {% set B01 = states('sensor.soulsens_dpid104_01') %}
              {% set B02 = states('sensor.soulsens_dpid104_02') %}
              {% set B03 = states('sensor.soulsens_dpid104_03') %}
              {% set PREi = 377 %}
              {% set B00i = ('0x' ~ B00) | int(base=16) %}
              {% set B01i = ('0x' ~ B01) | int(base=16) %}
              {% set B02i = ('0x' ~ B02) | int(base=16) %}
              {% set B03i = ('0x' ~ B03) | int(base=16) %}
              {% set CHKi = (PREi+B00i+B01i+B02i+B03i) % 256 %}
              {% set CHK = "%02x" % CHKi %}
              {{ PRE~B00~B01~B02~B03~CHK }}
        turn_off: # if the white light is "turned off" we will switch modes to the white light and turn off
          service: mqtt.publish
          data:
            topic: cmnd/your_tasmota_topic/SerialSend5
            retain: true
            payload_template: >
              {% set PRE = "55AA0006000868000004" %}
              {% set B00 = '00' %}
              {% set B01 = states('sensor.soulsens_dpid104_01') %}
              {% set B02 = states('sensor.soulsens_dpid104_02') %}
              {% set B03 = states('sensor.soulsens_dpid104_03') %}
              {% set PREi = 377 %}
              {% set B00i = ('0x' ~ B00) | int(base=16) %}
              {% set B01i = ('0x' ~ B01) | int(base=16) %}
              {% set B02i = ('0x' ~ B02) | int(base=16) %}
              {% set B03i = ('0x' ~ B03) | int(base=16) %}
              {% set CHKi = (PREi+B00i+B01i+B02i+B03i) % 256 %}
              {% set CHK = "%02x" % CHKi %}
              {{ PRE~B00~B01~B02~B03~CHK }}
        set_level:
          service: mqtt.publish
          data:
            topic: cmnd/your_tasmota_topic/SerialSend5
            retain: true
            payload_template: >
              {% set PRE = "55AA0006000868000004" %}
              {% set B00 = states('sensor.soulsens_dpid104_00') %}
              {% set B01 = states('sensor.soulsens_dpid104_01') %}
              {% set B02 = "%02x" % max(1, (((brightness|float)*15/255) | int)) %}
              {% set B03 = states('sensor.soulsens_dpid104_03') %}
              {% set PREi = 377 %}
              {% set B00i = ('0x' ~ B00) | int(base=16) %}
              {% set B01i = ('0x' ~ B01) | int(base=16) %}
              {% set B02i = ('0x' ~ B02) | int(base=16) %}
              {% set B03i = ('0x' ~ B03) | int(base=16) %}
              {% set CHKi = (PREi+B00i+B01i+B02i+B03i) % 256 %}
              {% set CHK = "%02x" % CHKi %}
              {{ PRE~B00~B01~B02~B03~CHK }}
        set_effect:
          service: mqtt.publish
          data:
            topic: cmnd/your_tasmota_topic/SerialSend5
            retain: true
            payload_template: >
              {% if effect == 'Ocean' %}
                {% set effect_val = '01' %}
              {% elif effect == 'Thunder' %}
                {% set effect_val = '02' %}
              {% elif effect == 'Rain' %}
                {% set effect_val = '03' %}
              {% elif effect == 'Stream' %}
                {% set effect_val = '04' %}
              {% elif effect == 'Rainforest' %}
                {% set effect_val = '05' %}
              {% elif effect == 'Wind' %}
                {% set effect_val = '06' %}
              {% elif effect == 'Deep space' %}
                {% set effect_val = '07' %}
              {% elif effect == 'Bird' %}
                {% set effect_val = '08' %}
              {% elif effect == 'Cricket' %}
                {% set effect_val = '09' %}
              {% elif effect == 'Whale' %}
                {% set effect_val = '0A' %}
              {% elif effect == 'White Noise' %}
                {% set effect_val = '0B' %}
              {% elif effect == 'Pink Noise' %}
                {% set effect_val = '0C' %}
              {% elif effect == 'Fan' %}
                {% set effect_val = '0D' %}
              {% elif effect == 'Hairdryer' %}
                {% set effect_val = '0E' %}
              {% elif effect == 'Lullaby' %}
                {% set effect_val = '0F' %}
              {% elif effect == 'Piano' %}
                {% set effect_val = '10' %}
              {% elif effect == 'Wind Chimes' %}
                {% set effect_val = '11' %}
              {% endif %}
              {% set PRE = "55AA0006000868000004" %}
              {% set B00 = states('sensor.soulsens_dpid104_00') %}
              {% set B01 = effect_val %}
              {% set B02 = states('sensor.soulsens_dpid104_02') %}
              {% set B03 = states('sensor.soulsens_dpid104_03') %}
              {% set PREi = 377 %}
              {% set B00i = ('0x' ~ B00) | int(base=16) %}
              {% set B01i = ('0x' ~ B01) | int(base=16) %}
              {% set B02i = ('0x' ~ B02) | int(base=16) %}
              {% set B03i = ('0x' ~ B03) | int(base=16) %}
              {% set CHKi = (PREi+B00i+B01i+B02i+B03i) % 256 %}
              {% set CHK = "%02x" % CHKi %}
              {{ PRE~B00~B01~B02~B03~CHK }}
